"""Hand-written, temporally-ordered combined episode prompts (one per chunk).

These were composed manually by reading each chunk's subtasks in
chunk_verification.txt: subtask actions are described in the order they are
executed (remove-phases before pack-phases when that is the temporal order),
consecutive subtasks sharing a verb+box are grouped, and box identity
(small/medium/large) is preserved. apply_prompts.py writes these into
chunk_verification.txt and chunks.json (combined_annotation). No templating —
this dict is the source of truth.
"""
PROMPTS = {
0: "Remove the Microfiber cloth and Sponge from the medium box, then pack the Cheez-It container, Altoids container, and Croissant into the medium box.",
1: "Remove the Pringles chip bag and Soccer ball plush from the large box, then pack the Nesquik container, Soda can, and Cinnamon Toast Crunch cereal into the large box.",
2: "Remove the Pink tumbler, Whiteboard eraser, and Soccer ball plush from the small box, then pack the Cheez-It container, Altoids container, and Box of M&Ms into the small box.",
3: "Pack the Cinnamon Toast Crunch cereal, Nesquik container, and sponge into the large box, then pack the Soda can and Pringles chip bag into the medium box, then pack the Microfiber cloth and Stuffed yak into the large box.",
4: "Pack the Cheez-It container, Soda can, Altoids container, and Liquid hand soap into the small box, then pack the sponge into the medium box.",
5: "Pack the Soda can, Nesquik container, and Pink tumbler into the small box, then remove the Soda can from the small box, then pack the Pink tumbler and Soda can into the small box, then pack the Altoids container, Donut, and Pringles chip bag into the large box.",
6: "Pack the spatula and Cling n' seal wrap into the large box, then pack the Soda can, Altoids container, and sponge into the small box.",
7: "Pack the Soda can and Pink tumbler into the small box, then pack the Cheez-It container, Altoids container, and sponge into the medium box.",
8: "Pack the Altoids container, Cheez-It container, and Whiteboard eraser into the small box, then pack the Box of M&Ms, sponge, Donut, and Croissant into the medium box.",
9: "Pack the Nesquik container and Soda can into the medium box, then pack the Cheez-It container and Cinnamon Toast Crunch cereal into the large box.",
10: "Pack the Microfiber cloth, Pink tumbler, Soda can, and Altoids container into the medium box, then pack the Cheez-It container and Nesquik container into the large box.",
11: "Pack the Soda can, Pink tumbler, and Nesquik container into the medium box, then pack the Altoids container, sponge, Microfiber cloth, Pringles chip bag, Soccer ball plush, croissant, and Whiteboard eraser into the large box.",
12: "Pack the Cheez-It container into the medium box, then pack the Altoids container and sponge into the small box, then pack the Microfiber cloth into the medium box, then pack the GoGo fruit pouch into the small box.",
13: "Pack the Soda can and Pink tumbler into the medium box, then pack the mustard and donut into the large box.",
14: "Pack the Cheez-It container, Altoids container, and Soda can into the small box, then pack the sponge and Microfiber cloth into the medium box.",
15: "Pack the Altoids container, sponge, and Whiteboard eraser into the small box.",
16: "Pack the Cheez-It container, Soda can, and Altoids container into the small box.",
17: "Pack the Cheez-It container and Whiteboard eraser into the small box, then pack the sponge and Soda can into the large box.",
18: "Pack the Nesquik container and Cinnamon Toast Crunch cereal into the medium box, then pack the Microfiber cloth, Marker, and Soccer ball plush into the large box.",
19: "Pack the Soda can, Cheez-It container, Nesquik container, and Croissant into the medium box, then pack the Pringles chip bag, donut, Altoids container, and Microfiber cloth into the small box.",
20: "Pack the Soda can, Soccer ball plush, GoGo fruit pouch, Pringles chip bag, and marker into the medium box, then pack the Cheez-It container and Cinnamon Toast Crunch cereal into the large box.",
21: "Pack the Soda can, Pringles chip bag, and Altoids container into the medium box, then pack the Soccer ball plush, Sponge, and Liquid hand soap into the small box.",
22: "Pack the Cinnamon Toast Crunch cereal, Nesquik container, Sponge, and Altoids container into the large box, then pack the Microfiber cloth into the medium box.",
23: "Pack the Cheez-It container, Whiteboard eraser, and Donut into the medium box, then pack the Box of M&Ms and sponge into the small box.",
24: "Pack the Nesquik container, Soda can, and Pink tumbler into the small box, then pack the Altoids container, Whiteboard eraser, and Microfiber cloth into the large box.",
25: "Remove the Box of M&Ms and Microfiber cloth from the medium box, then pack the Cheez-It container and Altoids container into the small box.",
26: "Pack the Cinnamon Toast Crunch cereal, Soccer ball plush, Pringles chip bag, Nesquik container, Soda can, and spatula into the large box.",
27: "Pack the Soda can and Pink tumbler into the small box, then pack the Altoids container, Cheez-It container, sponge, and Microfiber cloth into the large box.",
28: "Pack the Pringles chip bag and Altoids container into the small box, then pack the sponge into the medium box.",
29: "Pack the Stuffed yak and sponge into the medium box, then pack the Cling n' seal wrap, Whiteboard eraser, and donut into the large box.",
30: "Remove the Microfiber cloth and Whiteboard eraser from the large box, then remove the Sponge and Altoids container from the small box, then pack the Marker into the large box, then pack the Cheez-It container into the small box.",
31: "Pack the Soccer ball plush, Spatula, and Cling n' seal wrap into the large box.",
32: "Pack the Cheez-It container, Cinnamon Toast Crunch cereal, Microfiber cloth, Box of M&Ms, Nutella container, and Marker into the medium box.",
33: "Pack the Nesquik container, Soda can, and Pink tumbler into the small box, then pack the Cinnamon Toast Crunch cereal, Pringles chip bag, and Liquid hand soap into the large box.",
34: "Pack the Cheez-It container, Altoids container, Box of M&Ms, Donut, and GoGo fruit pouch into the medium box, then pack the Cinnamon Toast Crunch cereal, Microfiber cloth, and Marker into the large box.",
35: "Pack the Sponge, Altoids container, and Box of M&Ms into the small box, then pack the Nesquik container and Soda can into the large box.",
36: "Pack the Cheez-It container into the small box, then pack the Cinnamon Toast Crunch cereal, Soda can, Nesquik container, Box of M&Ms, Marker, Pringles chip bag, and Soccer ball plush into the large box.",
37: "Pack the GoGo fruit pouch, Donut, Croissant, and Baking soda into the medium box, then pack the Nutella container, Mustard, Liquid hand soap, and Microfiber cloth into the large box.",
38: "Pack the Pringles chip bag into the large box, then pack the Microfiber cloth into the small box, then pack the Marker into the large box, then pack the Altoids container into the small box.",
39: "Pack the Box of M&Ms and Cinnamon Toast Crunch cereal into the large box, then pack the Cheez-It container, Donut, and Croissant into the medium box.",
40: "Pack the Nesquik container, Soda can, Donut, Croissant, Nutella container, and GoGo fruit pouch into the medium box, then pack the Marker and Microfiber cloth into the large box.",
41: "Pack the Nesquik container, Soda can, and Pink tumbler into the large box, then pack the Altoids container and Sponge into the small box.",
42: "Pack the Altoids container, Sponge, and Whiteboard eraser into the small box.",
43: "Pack the Soda can, Pringles chip bag, and Pink tumbler into the small box.",
44: "Pack the Cheez-It container and Cinnamon Toast Crunch cereal into the medium box.",
45: "Pack the Soda can, Altoids container, and GoGo fruit pouch into the small box, then pack the Soccer ball plush into the large box.",
46: "Pack the Cinnamon Toast Crunch cereal, Cheez-It container, Microfiber cloth, Whiteboard eraser, Box of M&Ms, and Sponge into the medium box.",
47: "Pack the Pringles chip bag, Soda can, Sponge, and Pink tumbler into the large box, then pack the Liquid hand soap into the small box.",
48: "Pack the Nesquik container, Altoids container, and Donut into the small box, then pack the Soda can, Whiteboard eraser, and Sponge into the large box.",
49: "Pack the Cheez-It container, Altoids container, and Donut into the medium box, then pack the Cinnamon Toast Crunch cereal, Microfiber cloth, and Marker into the large box.",
50: "Pack the Nesquik container, Soda can, Pink tumbler, and Pringles chip bag into the large box, then pack the Altoids container and Sponge into the small box.",
51: "Pack the Cheez-It container, Baking soda, Donut, Croissant, and Nutella container into the medium box, then pack the Microfiber cloth, Stuffed yak, and Liquid hand soap into the large box.",
52: "Remove the Sponge and Microfiber cloth from the medium box, then pack the Cheez-It container, Altoids container, and Croissant into the medium box.",
53: "Remove the Pringles chip bag and Soccer ball plush from the large box, then pack the Nesquik container, Soda can, and Cinnamon Toast Crunch cereal into the large box.",
54: "Remove the Altoids container and Sponge from the small box, then remove the Whiteboard eraser and Microfiber cloth from the large box, then pack the Marker into the large box, then pack the Cheez-It container into the small box.",
55: "Remove the Pink tumbler, Whiteboard eraser, and Soccer ball plush from the small box, then pack the Cheez-It container, Altoids container, and Box of M&Ms into the small box.",
56: "Pack the Cinnamon Toast Crunch cereal, Soda can, and Pringles chip bag into the large box, then pack the Nesquik container, Microfiber cloth, Sponge, and Stuffed yak into the medium box.",
57: "Pack the Cheez-It container, Soda can, Altoids container, and Liquid hand soap into the small box, then pack the Sponge into the medium box.",
58: "Pack the Cling n' seal wrap, Spatula, and Soccer ball plush into the large box.",
59: "Pack the Soda can, Nesquik container, and Pink tumbler into the small box, then pack the Altoids container, Donut, and Pringles chip bag into the large box.",
60: "Pack the Cheez-It container, Cinnamon Toast Crunch cereal, Nutella container, Microfiber cloth, Box of M&Ms, and Marker into the medium box.",
61: "Pack the Nesquik container, Soda can, and Pink tumbler into the small box, then pack the Cinnamon Toast Crunch cereal, Pringles chip bag, and Liquid hand soap into the large box.",
62: "Pack the Spatula and Cling n' seal wrap into the large box, then pack the Soda can, Altoids container, and Sponge into the small box.",
63: "Pack the Soda can and Pink tumbler into the small box, then pack the Cheez-It container, Altoids container, and Sponge into the medium box.",
64: "Pack the Cheez-It container, Altoids container, Box of M&Ms, Donut, and GoGo fruit pouch into the medium box, then pack the Cinnamon Toast Crunch cereal, Microfiber cloth, and Marker into the large box.",
65: "Pack the Sponge, Altoids container, and Box of M&Ms into the small box, then pack the Nesquik container and Soda can into the large box.",
66: "Pack the Altoids container, Cheez-It container, and Whiteboard eraser into the small box, then pack the Box of M&Ms, Sponge, Donut, and Croissant into the medium box.",
67: "Pack the Nesquik container and Soda can into the medium box, then pack the Cheez-It container and Mustard into the large box.",
68: "Pack the Cheez-It container, Cinnamon Toast Crunch cereal, Nesquik container, and Soda can into the large box, then pack the Box of M&Ms, Marker, and Pringles chip bag into the small box, then pack the Soccer ball plush into the large box.",
69: "Pack the Soda can, Pink tumbler, and Altoids container into the medium box, then pack the Nesquik container, Cheez-It container, and Microfiber cloth into the large box.",
70: "Pack the Soda can, Pink tumbler, and Nesquik container into the medium box, then pack the Altoids container, Sponge, Microfiber cloth, Pringles chip bag, Soccer ball plush, Croissant, and Whiteboard eraser into the large box.",
71: "Pack the GoGo fruit pouch, Donut, Croissant, and Baking soda into the medium box, then pack the Nutella container, Mustard, Liquid hand soap, and Microfiber cloth into the large box.",
72: "Pack the Cheez-It container into the medium box, then pack the Altoids container and Sponge into the small box, then pack the Microfiber cloth into the medium box, then pack the GoGo fruit pouch into the small box.",
73: "Pack the Nesquik container into the medium box, then pack the Mustard and Donut into the large box.",
74: "Pack the Pringles chip bag into the large box, then pack the Microfiber cloth into the small box, then pack the Marker into the large box, then pack the Altoids container into the small box.",
75: "Pack the Box of M&Ms and Cinnamon Toast Crunch cereal into the large box, then pack the Cheez-It container, Donut, and Croissant into the medium box.",
76: "Pack the Cheez-It container, Altoids container, and Soda can into the small box, then pack the Sponge and Microfiber cloth into the medium box.",
77: "Pack the Nesquik container, Soda can, Donut, Croissant, Nutella container, and GoGo fruit pouch into the medium box, then pack the Marker and Microfiber cloth into the large box.",
78: "Pack the Nesquik container, Soda can, and Pink tumbler into the large box, then pack the Altoids container and Sponge into the small box.",
79: "Pack the Altoids container, Sponge, and Whiteboard eraser into the small box.",
80: "Pack the Soda can, Pringles chip bag, and Pink tumbler into the small box.",
81: "Pack the Cheez-It container and Cinnamon Toast Crunch cereal into the medium box.",
82: "Pack the Altoids container, Sponge, and Whiteboard eraser into the small box.",
83: "Pack the Soda can, Altoids container, and GoGo fruit pouch into the small box, then pack the Soccer ball plush into the large box.",
84: "Pack the Cheez-It container, Soda can, and Altoids container into the small box.",
85: "Pack the Cinnamon Toast Crunch cereal, Cheez-It container, Box of M&Ms, Whiteboard eraser, Sponge, and Microfiber cloth into the medium box.",
86: "Pack the Pringles chip bag, Soda can, Sponge, and Pink tumbler into the large box, then pack the Liquid hand soap into the small box.",
87: "Pack the Cheez-It container and Whiteboard eraser into the small box, then pack the Sponge and Soda can into the large box.",
88: "Pack the Nesquik container and Cinnamon Toast Crunch cereal into the medium box, then pack the Microfiber cloth, Marker, and Soccer ball plush into the large box.",
89: "Pack the Cheez-It container, Nesquik container, Donut, and Soda can into the medium box, then pack the Pringles chip bag, Altoids container, Croissant, and Microfiber cloth into the small box.",
90: "Pack the Soda can, GoGo fruit pouch, Pringles chip bag, Soccer ball plush, and Marker into the medium box, then pack the Mustard and Cheez-It container into the large box.",
91: "Pack the Nesquik container, Altoids container, Donut, and Nutella container into the small box, then pack the Soda can, Whiteboard eraser, and Sponge into the large box.",
92: "Pack the Soda can, Soccer ball plush, and Sponge into the small box, then pack the Liquid hand soap, Pringles chip bag, and Altoids container into the medium box.",
93: "Pack the Cinnamon Toast Crunch cereal and Nesquik container into the large box, then pack the Sponge, Altoids container, and Microfiber cloth into the medium box.",
94: "Pack the Cheez-It container, Altoids container, and Donut into the medium box, then pack the Cinnamon Toast Crunch cereal, Microfiber cloth, and Marker into the large box.",
95: "Pack the Nesquik container, Soda can, Pink tumbler, and Pringles chip bag into the large box, then pack the Altoids container and Sponge into the small box.",
96: "Pack the Cheez-It container, Whiteboard eraser, and Donut into the medium box, then pack the Box of M&Ms and Sponge into the small box.",
97: "Pack the Nesquik container, Soda can, and Pink tumbler into the small box, then pack the Altoids container, Whiteboard eraser, and Microfiber cloth into the large box.",
98: "Remove the Box of M&Ms and Microfiber cloth from the medium box, then pack the Cheez-It container and Altoids container into the small box.",
99: "Pack the Cinnamon Toast Crunch cereal, Soccer ball plush, Pringles chip bag, Soda can, Nesquik container, and Spatula into the large box.",
100: "Pack the Soda can and Pink tumbler into the small box, then pack the Altoids container, Cheez-It container, Sponge, and Microfiber cloth into the large box.",
101: "Pack the Pringles chip bag and Altoids container into the small box, then pack the Sponge into the medium box.",
102: "Pack the Cheez-It container, Baking soda, Donut, Croissant, and Nutella container into the medium box, then pack the Microfiber cloth, Stuffed yak, and Liquid hand soap into the large box.",
103: "Pack the Stuffed yak and Sponge into the medium box, then pack the Cling n' seal wrap, Whiteboard eraser, and Donut into the large box.",
104: "Remove the Sponge and Microfiber cloth from the medium box, then pack the Cheez-It container, Altoids container, and Croissant into the medium box.",
105: "Remove the Pringles chip bag and Soccer ball plush from the large box, then pack the Nesquik container, Soda can, and Cinnamon Toast Crunch cereal into the large box.",
106: "Remove the Altoids container and Sponge from the small box, then remove the Microfiber cloth and Whiteboard eraser from the large box, then pack the Marker into the large box, then pack the Cheez-It container into the small box.",
107: "Remove the Pink tumbler, Whiteboard eraser, and Soccer ball plush from the small box, then pack the Cheez-It container, Altoids container, and Box of M&Ms into the small box.",
108: "Pack the Cinnamon Toast Crunch cereal, Pringles chip bag, Soda can, and Nesquik container into the large box, then pack the Sponge and Microfiber cloth into the medium box, then pack the Stuffed yak into the large box.",
109: "Pack the Cheez-It container, Soda can, Altoids container, and Liquid hand soap into the small box, then pack the Sponge into the medium box.",
110: "Pack the Cling n' seal wrap, Soccer ball plush, and Spatula into the large box.",
111: "Pack the Soda can, Nesquik container, and Pink tumbler into the small box, then pack the Altoids container, Donut, and Pringles chip bag into the large box.",
112: "Pack the Cheez-It container, Cinnamon Toast Crunch cereal, Microfiber cloth, Box of M&Ms, Marker, and Nutella container into the medium box.",
113: "Pack the Nesquik container, Soda can, and Pink tumbler into the small box, then pack the Cinnamon Toast Crunch cereal, Pringles chip bag, and Liquid hand soap into the large box.",
114: "Pack the Spatula and Cling n' seal wrap into the large box, then pack the Soda can, Altoids container, and Sponge into the small box.",
115: "Pack the Soda can and Pink tumbler into the small box, then pack the Cheez-It container, Altoids container, and Sponge into the medium box.",
116: "Pack the Cheez-It container, Altoids container, Box of M&Ms, Donut, and GoGo fruit pouch into the medium box, then pack the Cinnamon Toast Crunch cereal, Microfiber cloth, and Marker into the large box.",
117: "Pack the Sponge, Altoids container, and Box of M&Ms into the small box, then pack the Nesquik container and Soda can into the large box.",
118: "Pack the Altoids container, Cheez-It container, and Whiteboard eraser into the small box, then pack the Box of M&Ms, Sponge, Donut, and Croissant into the medium box.",
119: "Pack the Nesquik container and Soda can into the medium box, then pack the Cheez-It container and Mustard into the large box.",
120: "Pack the Cheez-It container, Cinnamon Toast Crunch cereal, Nesquik container, Soda can, and Soccer ball plush into the large box, then pack the Pringles chip bag, Marker, and Box of M&Ms into the small box.",
121: "Pack the Nesquik container, Soda can, and Cheez-It container into the medium box, then pack the Pink tumbler, Microfiber cloth, and Altoids container into the large box.",
122: "Pack the Soda can, Pink tumbler, and Nesquik container into the medium box, then pack the Altoids container, Sponge, Microfiber cloth, Pringles chip bag, Soccer ball plush, Croissant, and Whiteboard eraser into the large box.",
123: "Pack the GoGo fruit pouch, Donut, Croissant, and Baking soda into the medium box, then pack the Nutella container, Mustard, Liquid hand soap, and Microfiber cloth into the large box.",
124: "Pack the Cheez-It container into the medium box, then pack the Altoids container and Sponge into the small box, then pack the Microfiber cloth into the medium box, then pack the GoGo fruit pouch into the small box.",
125: "Pack the Nesquik container into the medium box, then pack the Mustard and Donut into the large box.",
126: "Pack the Pringles chip bag into the large box, then pack the Microfiber cloth into the small box, then pack the Marker into the large box, then pack the Altoids container into the small box.",
127: "Pack the Box of M&Ms and Cinnamon Toast Crunch cereal into the large box, then pack the Cheez-It container, Donut, and Croissant into the medium box.",
128: "Pack the Cheez-It container, Altoids container, and Soda can into the small box, then pack the Sponge and Microfiber cloth into the medium box.",
129: "Pack the Nesquik container, Soda can, Donut, Croissant, Nutella container, and GoGo fruit pouch into the medium box, then pack the Marker and Microfiber cloth into the large box.",
130: "Pack the Nesquik container, Soda can, and Pink tumbler into the large box, then pack the Altoids container and Sponge into the small box.",
131: "Pack the Altoids container, Sponge, and Whiteboard eraser into the small box.",
132: "Pack the Soda can, Pringles chip bag, and Pink tumbler into the small box.",
133: "Pack the Cheez-It container and Cinnamon Toast Crunch cereal into the medium box.",
134: "Pack the Altoids container, Sponge, and Whiteboard eraser into the small box.",
135: "Pack the Soda can, Altoids container, and GoGo fruit pouch into the small box, then pack the Soccer ball plush into the large box.",
136: "Pack the Cheez-It container, Soda can, and Altoids container into the small box.",
137: "Pack the Cinnamon Toast Crunch cereal, Cheez-It container, Sponge, Whiteboard eraser, Microfiber cloth, and Box of M&Ms into the medium box.",
138: "Pack the Pringles chip bag, Soda can, Sponge, and Pink tumbler into the large box, then pack the Liquid hand soap into the small box.",
139: "Pack the Cheez-It container and Whiteboard eraser into the small box, then pack the Sponge and Soda can into the large box.",
140: "Pack the Nesquik container and Cinnamon Toast Crunch cereal into the medium box, then pack the Microfiber cloth, Marker, and Soccer ball plush into the large box.",
141: "Pack the Nesquik container, Soda can, Cheez-It container, Donut, and Altoids container into the medium box, then pack the Croissant, Pringles chip bag, and Microfiber cloth into the small box.",
142: "Pack the Soda can, Mustard, GoGo fruit pouch, Marker, and Soccer ball plush into the medium box, then pack the Cheez-It container and Pringles chip bag into the large box.",
143: "Pack the Nesquik container, Altoids container, Donut, Nutella container, and Croissant into the small box, then pack the Soda can, Whiteboard eraser, and Sponge into the large box.",
144: "Pack the Soda can, Soccer ball plush, and Sponge into the small box, then pack the Liquid hand soap, Altoids container, and Pringles chip bag into the medium box.",
145: "Pack the Nesquik container and Cinnamon Toast Crunch cereal into the large box, then pack the Altoids container, Microfiber cloth, and Sponge into the medium box.",
146: "Pack the Cheez-It container, Altoids container, and Donut into the medium box, then pack the Cinnamon Toast Crunch cereal, Microfiber cloth, and Marker into the large box.",
147: "Pack the Nesquik container, Soda can, Pink tumbler, and Pringles chip bag into the large box, then pack the Altoids container and Sponge into the small box.",
148: "Pack the Cheez-It container, Whiteboard eraser, and Donut into the medium box, then pack the Box of M&Ms and Sponge into the small box.",
149: "Pack the Nesquik container, Soda can, and Pink tumbler into the small box, then pack the Altoids container, Whiteboard eraser, and Microfiber cloth into the large box.",
150: "Remove the Box of M&Ms and Microfiber cloth from the medium box, then pack the Cheez-It container and Altoids container into the small box.",
151: "Pack the Nesquik container, Soda can, Pringles chip bag, Cinnamon Toast Crunch cereal, Soccer ball plush, and Spatula into the large box.",
152: "Pack the Soda can and Pink tumbler into the small box, then pack the Altoids container, Cheez-It container, Sponge, and Microfiber cloth into the large box.",
153: "Pack the Pringles chip bag and Altoids container into the small box, then pack the Sponge into the medium box.",
154: "Pack the Cheez-It container, Baking soda, Donut, Croissant, and Nutella container into the medium box, then pack the Microfiber cloth, Stuffed yak, and Liquid hand soap into the large box.",
155: "Pack the Stuffed yak and Sponge into the medium box, then pack the Cling n' seal wrap, Whiteboard eraser, and Donut into the large box.",
156: "Remove the Microfiber cloth and Sponge from the medium box, then pack the Cheez-It container, Altoids container, and Croissant into the medium box.",
157: "Remove the Soccer ball plush and Pringles chip bag from the large box, then pack the Nesquik container, Soda can, and Cinnamon Toast Crunch cereal into the large box.",
158: "Remove the Microfiber cloth and Whiteboard eraser from the large box, then remove the Sponge and Altoids container from the small box, then pack the Marker into the large box, then pack the Cheez-It container into the small box.",
159: "Remove the Pink tumbler, Whiteboard eraser, and Soccer ball plush from the small box, then pack the Cheez-It container, Altoids container, and Box of M&Ms into the small box.",
160: "Pack the Cinnamon Toast Crunch cereal, Microfiber cloth, and Sponge into the large box, then pack the Nesquik container, Pringles chip bag, and Soda can into the medium box, then pack the Stuffed yak into the large box.",
161: "Pack the Cheez-It container, Soda can, Altoids container, and Liquid hand soap into the small box, then pack the Sponge into the medium box.",
162: "Pack the Spatula, Soccer ball plush, and Cling n' seal wrap into the large box.",
163: "Pack the Soda can, Nesquik container, and Pink tumbler into the small box, then pack the Altoids container, Donut, and Pringles chip bag into the large box.",
164: "Pack the Cinnamon Toast Crunch cereal, Cheez-It container, Microfiber cloth, Marker, Box of M&Ms, and Nutella container into the medium box.",
165: "Pack the Nesquik container, Soda can, and Pink tumbler into the small box, then pack the Cinnamon Toast Crunch cereal, Pringles chip bag, and Liquid hand soap into the large box.",
166: "Pack the Spatula and Cling n' seal wrap into the large box, then pack the Soda can, Altoids container, and Sponge into the small box.",
167: "Pack the Soda can and Pink tumbler into the small box, then pack the Cheez-It container, Altoids container, and Sponge into the medium box.",
168: "Pack the Cheez-It container, Altoids container, Box of M&Ms, Donut, and GoGo fruit pouch into the medium box, then pack the Cinnamon Toast Crunch cereal, Microfiber cloth, and Marker into the large box.",
169: "Pack the Sponge, Altoids container, and Box of M&Ms into the small box, then pack the Nesquik container and Soda can into the large box.",
170: "Pack the Altoids container, Cheez-It container, and Whiteboard eraser into the small box, then pack the Box of M&Ms, Sponge, Donut, and Croissant into the medium box.",
171: "Pack the Nesquik container and Soda can into the medium box, then pack the Cheez-It container and Mustard into the large box.",
172: "Pack the Cheez-It container, Cinnamon Toast Crunch cereal, Nesquik container, Soda can, and Pringles chip bag into the large box, then pack the Box of M&Ms and Soccer ball plush into the small box, then pack the Marker into the large box.",
173: "Pack the Nesquik container, Soda can, Altoids container, and Microfiber cloth into the medium box, then pack the Pink tumbler and Cheez-It container into the large box.",
174: "Pack the Soda can, Pink tumbler, and Nesquik container into the medium box, then pack the Altoids container, Sponge, Microfiber cloth, Pringles chip bag, Soccer ball plush, Croissant, and Whiteboard eraser into the large box.",
175: "Pack the GoGo fruit pouch, Donut, Croissant, and Baking soda into the medium box, then pack the Nutella container, Mustard, Liquid hand soap, and Microfiber cloth into the large box.",
176: "Pack the Cheez-It container into the medium box, then pack the Altoids container and Sponge into the small box, then pack the Microfiber cloth into the medium box, then pack the GoGo fruit pouch into the small box.",
177: "Pack the Nesquik container into the medium box, then pack the Mustard and Donut into the large box.",
178: "Pack the Pringles chip bag into the large box, then pack the Microfiber cloth into the small box, then pack the Marker into the large box, then pack the Altoids container into the small box.",
179: "Pack the Box of M&Ms and Cinnamon Toast Crunch cereal into the large box, then pack the Cheez-It container, Donut, and Croissant into the medium box.",
180: "Pack the Cheez-It container, Altoids container, and Soda can into the small box, then pack the Sponge and Microfiber cloth into the medium box.",
181: "Pack the Nesquik container, Soda can, Donut, Croissant, Nutella container, and GoGo fruit pouch into the medium box, then pack the Marker and Microfiber cloth into the large box.",
182: "Pack the Nesquik container, Soda can, and Pink tumbler into the large box, then pack the Altoids container and Sponge into the small box.",
183: "Pack the Altoids container, Sponge, and Whiteboard eraser into the small box.",
184: "Pack the Soda can, Pringles chip bag, and Pink tumbler into the small box.",
185: "Pack the Cheez-It container and Cinnamon Toast Crunch cereal into the medium box.",
186: "Pack the Altoids container, Sponge, and Whiteboard eraser into the small box.",
187: "Pack the Soda can, Altoids container, and GoGo fruit pouch into the small box, then pack the Soccer ball plush into the large box.",
188: "Pack the Cheez-It container, Soda can, and Altoids container into the small box.",
189: "Pack the Cinnamon Toast Crunch cereal, Cheez-It container, Microfiber cloth, Sponge, Box of M&Ms, and Whiteboard eraser into the medium box.",
190: "Pack the Pringles chip bag, Soda can, Sponge, and Pink tumbler into the large box, then pack the Liquid hand soap into the small box.",
191: "Pack the Cheez-It container and Whiteboard eraser into the small box, then pack the Sponge and Soda can into the large box.",
192: "Pack the Nesquik container and Cinnamon Toast Crunch cereal into the medium box, then pack the Microfiber cloth, Marker, and Soccer ball plush into the large box.",
193: "Pack the Cheez-It container, Nesquik container, Soda can, and Microfiber cloth into the medium box, then pack the Donut, Altoids container, Croissant, and Pringles chip bag into the small box.",
194: "Pack the Cheez-It container, Mustard, Marker, GoGo fruit pouch, and Soda can into the medium box, then pack the Soccer ball plush and Pringles chip bag into the large box.",
195: "Pack the Nesquik container, Altoids container, and Donut into the small box, then pack the Soda can, Whiteboard eraser, and Sponge into the large box.",
196: "Pack the Soda can, Altoids container, and Sponge into the small box, then pack the Pringles chip bag, Liquid hand soap, and Soccer ball plush into the medium box.",
197: "Pack the Cinnamon Toast Crunch cereal, Nesquik container, Sponge, and Altoids container into the large box, then pack the Microfiber cloth into the medium box.",
198: "Pack the Cheez-It container, Altoids container, and Donut into the medium box, then pack the Cinnamon Toast Crunch cereal, Microfiber cloth, and Marker into the large box.",
199: "Pack the Nesquik container, Soda can, Pink tumbler, and Pringles chip bag into the large box, then pack the Altoids container and Sponge into the small box.",
200: "Pack the Cheez-It container, Whiteboard eraser, and Donut into the medium box, then pack the Box of M&Ms and Sponge into the small box.",
201: "Pack the Nesquik container, Soda can, and Pink tumbler into the small box, then pack the Altoids container, Whiteboard eraser, and Microfiber cloth into the large box.",
202: "Remove the Box of M&Ms and Microfiber cloth from the medium box, then pack the Cheez-It container and Altoids container into the small box.",
203: "Pack the Cinnamon Toast Crunch cereal, Spatula, Soccer ball plush, Nesquik container, Soda can, and Pringles chip bag into the large box.",
204: "Pack the Soda can and Pink tumbler into the small box, then pack the Altoids container, Cheez-It container, Sponge, and Microfiber cloth into the large box.",
205: "Pack the Pringles chip bag and Altoids container into the small box, then pack the Sponge into the medium box.",
206: "Pack the Cheez-It container, Baking soda, Donut, Croissant, and Nutella container into the medium box, then pack the Microfiber cloth, Stuffed yak, and Liquid hand soap into the large box.",
207: "Pack the Stuffed yak and Sponge into the medium box, then pack the Cling n' seal wrap, Whiteboard eraser, and Donut into the large box.",
208: "Remove the Microfiber cloth and Sponge from the medium box, then pack the Cheez-It container, Altoids container, and Croissant into the medium box.",
209: "Remove the Pringles chip bag and Soccer ball plush from the large box, then pack the Nesquik container, Soda can, and Cinnamon Toast Crunch cereal into the large box.",
210: "Remove the Microfiber cloth and Whiteboard eraser from the large box, then remove the Sponge and Altoids container from the small box, then pack the Marker into the large box, then pack the Cheez-It container into the small box.",
211: "Remove the Pink tumbler, Whiteboard eraser, and Soccer ball plush from the small box, then pack the Cheez-It container, Altoids container, and Box of M&Ms into the small box.",
212: "Pack the Cinnamon Toast Crunch cereal, Nesquik container, and Soda can into the medium box, then pack the Pringles chip bag, Microfiber cloth, Sponge, and Stuffed yak into the large box.",
213: "Pack the Cheez-It container, Soda can, Altoids container, and Liquid hand soap into the small box, then pack the Sponge into the medium box.",
214: "Pack the Cling n' seal wrap, Soccer ball plush, and Spatula into the large box.",
215: "Pack the Soda can, Nesquik container, and Pink tumbler into the small box, then pack the Altoids container, Donut, and Pringles chip bag into the large box.",
216: "Pack the Cinnamon Toast Crunch cereal, Cheez-It container, Nutella container, Microfiber cloth, Box of M&Ms, and Marker into the medium box.",
217: "Pack the Nesquik container, Soda can, and Pink tumbler into the small box, then pack the Cinnamon Toast Crunch cereal, Pringles chip bag, and Liquid hand soap into the large box.",
218: "Pack the Spatula and Cling n' seal wrap into the large box, then pack the Soda can, Altoids container, and Sponge into the small box.",
219: "Pack the Soda can and Pink tumbler into the small box, then pack the Cheez-It container, Altoids container, and Sponge into the medium box.",
220: "Pack the Cheez-It container, Altoids container, Box of M&Ms, Donut, and Gogo fruit pouch into the medium box, then pack the Cinnamon Toast Crunch cereal, Microfiber cloth, and Marker into the large box.",
221: "Pack the Sponge, Altoids container, and Box of M&Ms into the small box, then pack the Nesquik container and Soda can into the large box.",
222: "Pack the Altoids container, Cheez-It container, and Whiteboard eraser into the small box, then pack the Box of M&Ms, Sponge, Donut, and Croissant into the medium box.",
223: "Pack the Nesquik container and Soda can into the medium box, then pack the Cheez-It container and Mustard into the large box.",
224: "Pack the Soccer ball plush, Marker, Nesquik container, Pringles chip bag, Soda can, and Cinnamon Toast Crunch cereal into the large box, then pack the Cheez-It container and Box of M&Ms into the small box.",
225: "Pack the Pink tumbler, Soda can, Altoids container, Cheez-It container, and Microfiber cloth into the medium box, then pack the Nesquik container into the large box.",
226: "Pack the Soda can, Pink tumbler, and Nesquik container into the medium box, then pack the Altoids container, Sponge, Microfiber cloth, Pringles chip bag, Soccer ball plush, Croissant, and Whiteboard eraser into the large box.",
227: "Pack the GoGo fruit pouch, Donut, Croissant, and Baking soda into the medium box, then pack the Nutella container, Mustard, Liquid hand soap, and Microfiber cloth into the large box.",
228: "Pack the Cheez-It container into the medium box, then pack the Altoids container and Sponge into the small box, then pack the Microfiber cloth into the medium box, then pack the GoGo fruit pouch into the small box.",
229: "Pack the Nesquik container into the medium box, then pack the Mustard and Donut into the large box.",
230: "Pack the Pringles chip bag into the large box, then pack the Microfiber cloth into the small box, then pack the Marker into the large box, then pack the Altoids container into the small box.",
231: "Pack the Box of M&Ms and Cinnamon Toast Crunch cereal into the large box, then pack the Cheez-It container, Donut, and Croissant into the medium box.",
232: "Pack the Cheez-It container, Altoids container, and Soda can into the small box, then pack the Sponge and Microfiber cloth into the medium box.",
233: "Pack the Nesquik container, Soda can, Donut, Croissant, Nutella container, and GoGo fruit pouch into the medium box, then pack the Marker and Microfiber cloth into the large box.",
234: "Pack the Nesquik container, Soda can, and Pink tumbler into the large box, then pack the Altoids container and Sponge into the small box.",
235: "Pack the Altoids container, Sponge, and Whiteboard eraser into the small box.",
236: "Pack the Soda can, Pringles chip bag, and Pink tumbler into the small box.",
237: "Pack the Cheez-It container and Cinnamon Toast Crunch cereal into the medium box.",
238: "Pack the Altoids container, Sponge, and Whiteboard eraser into the small box.",
239: "Pack the Soda can, Altoids container, and GoGo fruit pouch into the small box, then pack the Soccer ball plush into the large box.",
240: "Pack the Cheez-It container, Soda can, and Altoids container into the small box.",
241: "Pack the Cinnamon Toast Crunch cereal, Cheez-It container, Whiteboard eraser, Microfiber cloth, Sponge, and Box of M&Ms into the medium box.",
242: "Pack the Pringles chip bag, Soda can, Sponge, and Pink tumbler into the large box, then pack the Liquid hand soap into the small box.",
243: "Pack the Cheez-It container and Whiteboard eraser into the small box, then pack the Sponge and Soda can into the large box.",
244: "Pack the Nesquik container and Cinnamon Toast Crunch cereal into the medium box, then pack the Microfiber cloth, Marker, and Soccer ball plush into the large box.",
245: "Pack the Microfiber cloth, Altoids container, Soda can, Croissant, and Cheez-It container into the medium box, then pack the Nesquik container and Pringles chip bag into the small box.",
246: "Pack the Mustard, Pringles chip bag, Soccer ball plush, Soda can, GoGo fruit pouch, and Marker into the medium box, then pack the Cheez-It container into the large box.",
247: "Pack the Nesquik container, Altoids container, and Donut into the small box, then pack the Soda can, Whiteboard eraser, and Sponge into the large box.",
248: "Pack the Liquid hand soap, Soccer ball plush, and Pringles chip bag into the medium box, then pack the Soda can, Altoids container, and Sponge into the small box.",
249: "Pack the Cinnamon Toast Crunch cereal, Microfiber cloth, and Nesquik container into the large box, then pack the Altoids container and Sponge into the medium box.",
250: "Pack the Cheez-It container, Altoids container, and Donut into the medium box, then pack the Cinnamon Toast Crunch cereal, Microfiber cloth, and Marker into the large box.",
251: "Pack the Nesquik container, Soda can, Pink tumbler, and Pringles chip bag into the large box, then pack the Altoids container and Sponge into the small box.",
252: "Pack the Cheez-It container, Whiteboard eraser, and Donut into the medium box, then pack the Box of M&Ms and Sponge into the small box.",
253: "Pack the Nesquik container, Soda can, and Pink tumbler into the small box, then pack the Altoids container, Whiteboard eraser, and Microfiber cloth into the large box.",
254: "Remove the Box of M&Ms and Microfiber cloth from the medium box, then pack the Cheez-It container and Altoids container into the small box.",
255: "Pack the Soccer ball plush, Cinnamon Toast Crunch cereal, Nesquik container, Soda can, Pringles chip bag, and Spatula into the large box.",
256: "Pack the Soda can and Pink tumbler into the small box, then pack the Altoids container, Cheez-It container, Sponge, and Microfiber cloth into the large box.",
257: "Pack the Pringles chip bag and Altoids container into the small box, then pack the Sponge into the medium box.",
258: "Pack the Cheez-It container, Baking soda, Donut, Croissant, and Nutella container into the medium box, then pack the Microfiber cloth, Stuffed yak, and Liquid hand soap into the large box.",
259: "Pack the Stuffed yak and Sponge into the medium box, then pack the Cling n' seal wrap, Whiteboard eraser, and Donut into the large box.",
260: "Remove the Sponge and Microfiber cloth from the medium box, then pack the Cheez-It container, Altoids container, and Croissant into the medium box.",
261: "Remove the Pringles chip bag and Soccer ball plush from the large box, then pack the Nesquik container, Soda can, and Cinnamon Toast Crunch cereal into the large box.",
262: "Remove the Microfiber cloth and Whiteboard eraser from the large box, then remove the Sponge and Altoids container from the small box, then pack the Marker into the large box, then pack the Cheez-It container into the small box.",
263: "Remove the Pink tumbler, Whiteboard eraser, and Soccer ball plush from the small box, then pack the Cheez-It container, Altoids container, and Box of M&Ms into the small box.",
264: "Pack the Nesquik container, Microfiber cloth, Soda can, Sponge, and Pringles chip bag into the medium box, then pack the Cinnamon Toast Crunch cereal and Stuffed yak into the large box.",
265: "Pack the Cheez-It container, Soda can, Altoids container, and Liquid hand soap into the small box, then pack the Sponge into the medium box.",
266: "Pack the Spatula, Soccer ball plush, and Cling n' seal wrap into the large box.",
267: "Pack the Soda can, Nesquik container, and Pink tumbler into the small box, then pack the Altoids container, Donut, and Pringles chip bag into the large box.",
268: "Pack the Cinnamon Toast Crunch cereal, Cheez-It container, Box of M&Ms, Nutella container, Microfiber cloth, and Marker into the medium box.",
269: "Pack the Nesquik container, Soda can, and Pink tumbler into the small box, then pack the Cinnamon Toast Crunch cereal, Pringles chip bag, and Liquid hand soap into the large box.",
270: "Pack the Spatula and Cling n' seal wrap into the large box, then pack the Soda can, Altoids container, and Sponge into the small box.",
271: "Pack the Soda can and Pink tumbler into the small box, then pack the Cheez-It container, Altoids container, and Sponge into the medium box.",
272: "Pack the Cheez-It container, Altoids container, Box of M&Ms, Donut, and GoGo fruit pouch into the medium box, then pack the Cinnamon Toast Crunch cereal, Microfiber cloth, and Marker into the large box.",
273: "Pack the Sponge, Altoids container, and Box of M&Ms into the small box, then pack the Nesquik container and Soda can into the large box.",
274: "Pack the Altoids container, Cheez-It container, and Whiteboard eraser into the small box, then pack the Box of M&Ms, Sponge, Donut, and Croissant into the medium box.",
275: "Pack the Nesquik container and Soda can into the medium box, then pack the Cheez-It container and Mustard into the large box.",
276: "Pack the Nesquik container, Cinnamon Toast Crunch cereal, Pringles chip bag, Marker, Soda can, and Cheez-It container into the large box, then pack the Soccer ball plush and Box of M&Ms into the small box.",
277: "Pack the Pink tumbler, Microfiber cloth, Soda can, Altoids container, and Nesquik container into the medium box, then pack the Cheez-It container into the large box.",
278: "Pack the Soda can, Pink tumbler, and Nesquik container into the medium box, then pack the Altoids container, Sponge, Microfiber cloth, Pringles chip bag, Soccer ball plush, Croissant, and Whiteboard eraser into the large box.",
279: "Pack the GoGo fruit pouch, Donut, Croissant, and Baking soda into the medium box, then pack the Nutella container, Mustard, Liquid hand soap, and Microfiber cloth into the large box.",
280: "Pack the Cheez-It container into the medium box, then pack the Altoids container and Sponge into the small box, then pack the Microfiber cloth into the medium box, then pack the GoGo fruit pouch into the small box.",
281: "Pack the Nesquik container into the medium box, then pack the Mustard and Donut into the large box.",
282: "Pack the Pringles chip bag into the large box, then pack the Microfiber cloth into the small box, then pack the Marker into the large box, then pack the Altoids container into the small box.",
283: "Pack the Box of M&Ms and Cinnamon Toast Crunch cereal into the large box, then pack the Cheez-It container, Donut, and Croissant into the medium box.",
284: "Pack the Cheez-It container, Altoids container, and Soda can into the small box, then pack the Sponge and Microfiber cloth into the medium box.",
285: "Pack the Nesquik container, Soda can, Donut, Croissant, Nutella container, and GoGo fruit pouch into the medium box, then pack the Marker and Microfiber cloth into the large box.",
286: "Pack the Nesquik container, Soda can, and Pink tumbler into the large box, then pack the Altoids container and Sponge into the small box.",
287: "Pack the Altoids container, Sponge, and Whiteboard eraser into the small box.",
288: "Pack the Soda can, Pringles chip bag, and Pink tumbler into the small box.",
289: "Pack the Cheez-It container and Cinnamon Toast Crunch cereal into the medium box.",
290: "Pack the Altoids container, Sponge, and Whiteboard eraser into the small box.",
291: "Pack the Soda can, Altoids container, and GoGo fruit pouch into the small box, then pack the Soccer ball plush into the large box.",
292: "Pack the Cheez-It container, Soda can, and Altoids container into the small box.",
293: "Pack the Cheez-It container, Cinnamon Toast Crunch cereal, Whiteboard eraser, Microfiber cloth, Box of M&Ms, and Sponge into the medium box.",
294: "Pack the Pringles chip bag, Soda can, Sponge, and Pink tumbler into the large box, then pack the Liquid hand soap into the small box.",
295: "Pack the Cheez-It container and Whiteboard eraser into the small box, then pack the Sponge and Soda can into the large box.",
296: "Pack the Nesquik container and Cinnamon Toast Crunch cereal into the medium box, then pack the Microfiber cloth, Marker, and Soccer ball plush into the large box.",
297: "Pack the Nesquik container, Cheez-It container, Soda can, Donut, Altoids container, and Croissant into the medium box, then pack the Pringles chip bag and Microfiber cloth into the small box.",
298: "Pack the GoGo fruit pouch, Soccer ball plush, Mustard, Marker, Soda can, and Pringles chip bag into the medium box, then pack the Cheez-It container into the large box.",
299: "Pack the Nesquik container, Altoids container, Donut, and Nutella container into the small box, then pack the Soda can, Whiteboard eraser, and Sponge into the large box.",
300: "Pack the Liquid hand soap, Soccer ball plush, and Soda can into the medium box, then pack the Pringles chip bag, Altoids container, and Sponge into the small box.",
301: "Pack the Nesquik container, Microfiber cloth, and Sponge into the medium box, then pack the Cinnamon Toast Crunch cereal and Altoids container into the large box.",
302: "Pack the Cheez-It container, Altoids container, and Donut into the medium box, then pack the Cinnamon Toast Crunch cereal, Microfiber cloth, and Marker into the large box.",
303: "Pack the Nesquik container, Soda can, Pink tumbler, and Pringles chip bag into the large box, then pack the Altoids container and Sponge into the small box.",
304: "Pack the Cheez-It container, Whiteboard eraser, and Donut into the medium box, then pack the Box of M&Ms and Sponge into the small box.",
305: "Pack the Nesquik container, Soda can, and Pink tumbler into the small box, then pack the Altoids container, Whiteboard eraser, and Microfiber cloth into the large box.",
306: "Remove the Box of M&Ms and Microfiber cloth from the medium box, then pack the Cheez-It container and Altoids container into the small box.",
307: "Pack the Cinnamon Toast Crunch cereal, Nesquik container, Pringles chip bag, Soda can, Soccer ball plush, and Spatula into the large box.",
308: "Pack the Soda can and Pink tumbler into the small box, then pack the Altoids container, Cheez-It container, Sponge, and Microfiber cloth into the large box.",
309: "Pack the Pringles chip bag and Altoids container into the small box, then pack the Sponge into the medium box.",
310: "Pack the Cheez-It container, Baking soda, Donut, Croissant, and Nutella container into the medium box, then pack the Microfiber cloth, Stuffed yak, and Liquid hand soap into the large box.",
311: "Pack the Stuffed yak and Sponge into the medium box, then pack the Cling n' seal wrap, Whiteboard eraser, and Donut into the large box.",
}
